# Generated by Django 2.0.7 on 2018-07-28 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('schedule', models.DateField()),
                ('totalPlaces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fritickets.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('remark', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='eventtickets',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fritickets.Tarif'),
        ),
        migrations.AddField(
            model_name='event',
            name='availableTarifs',
            field=models.ManyToManyField(to='fritickets.Tarif'),
        ),
        migrations.AddField(
            model_name='event',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fritickets.Show'),
        ),
        migrations.AddField(
            model_name='booking',
            name='eventTickets',
            field=models.ManyToManyField(to='fritickets.EventTickets'),
        ),
        migrations.AddField(
            model_name='booking',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fritickets.Person'),
        ),
    ]
