# Generated by Django 2.0.7 on 2018-07-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritickets', '0003_auto_20180729_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(max_length=30)),
                ('eventTickets', models.ManyToManyField(to='fritickets.EventTickets')),
            ],
        ),
        migrations.AddField(
            model_name='tarif',
            name='isAdminOnly',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='isSystemOnly',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
