# Generated by Django 2.0.7 on 2018-08-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fritickets', '0006_auto_20180806_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
